### ISSUE TITLE
img2sixel not truncating output file

### ISSUE THREAD

**Issue by set135** [saitoha/libsixel#57] opened 2017-02-01 07:01 UTC
# img2sixel  -o out.sxl foo.jpg

works good, then...

# img2sixel -e -i  -o out.sxl foo.jpg

results in a file with the mono image followed by lots of garbage

(this makes a mono output, so smaller), but the file 'out.sxl' remains the same size, and cat'ing this file
to a terminal (or printer) results in lots of garbage at the end from the first conversion? Things work
as expected if you remove the 'out.sxl' file in between. I am not sure how this is happening, because
a casual glance at the source looked like correct use of fopen(), but an strace shows an open without
truncation. Using version 1.7.2

**Comment by saitoha** [comment] 2017-02-21 16:17
1. Can you try v1.7.3? I had received similar report at half a year ago. It fixed by 9c77782.
2. Can you attach the sample sixel file  'out.xsl' ?
3. Please tell me, what is your terminal?

**Comment by set135** [comment] 2017-02-26 03:45
rm -f out-1.sxl out-2.sxl
img2sixel -o out-1.sxl logo.jpg
ls -lh out-1.sxl
-rw------- 1 set set 60K 2017.02.25 10:25:19 pm out-1.sxl
(img looks good in mlterm)
img2sixel -e -i -o out-1.sxl logo.jpg
ls -lh out-1.sxl
-rw------- 1 set set 60K 2017.02.25 10:25:19 pm out-1.sxl
(img *should* be smaller, garbage follows image in mlterm)
img2sixel -e -i -o out-2.sxl logo.jpg
ls -lh out-2.sxl
-rw------- 1 set set 3.9K 2017.02.25 10:26:05 pm out-2.sxl
out-2.sxl looks as expected in mlterm

Attached (corrupt) out-1.sxl, out-2.sxl, logo.jpg in zip
Using libsixel-1.7.3

[files.zip](https://github.com/saitoha/libsixel/files/801711/files.zip)

**Comment by saitoha** [comment] 2017-02-26 12:18
Unfortunately, I can't reproduce it in my environment. Additional information is needed.
Can you attach the config.log created by ./configure in your build directory?

**Comment by set135** [comment] 2017-02-28 04:26
src/encoder.c.orig  2017-02-27 23:05:52.962405054 -0500
+++ src/encoder.c       2017-02-27 23:06:16.000204738 -0500
@@ -1275,7 +1275,7 @@
                 close(encoder->outfd);
             }
             encoder->outfd = open(value,
-                                  O_RDWR|O_CREAT,
+                                  O_RDWR|O_CREAT|O_TRUNC,
                                   S_IREAD|S_IWRITE);
         }
         break;
img2sixel parses the option and calls encoder.c:sixel_encoder_setopt() where the 
file is opened without truncation. This patch fixes the bad behaviour I see. No idea if
the encoder might actually want to seek around in an output file, or why this is how the
output file opened.
But this is the code that gets executed in my example, and fails to truncate the output file,
such that writing to the same file again with a smaller size leaves behind the original output
as garbage.

hmmm. that preview looks messed up but the patch just adds O_TRUNC to the open function
at line 1275 in src/encoder.c

**Comment by saitoha** [comment] 2018-06-08 14:30
@set135 Finally I can reproduce it. libsixel-1.8 includes the fix for this issue(c121c9b).

**Closed by saitoha** 2018-06-08 14:30 UTC
